const simpleprojects = [
  {
    name: "",
    githubLink: "https://victorblade38.github.io/NFT-preview-card-component/",
    about: "A simple NFT preview card component",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/interactive-rating-component/",
    about: "A simple interactive rating component",
    completed: true,
    techStack: ["HTML", "TailwindCss", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/result-summary-component/",
    about: "A simple result summary component",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink:
      "https://github.com/Victorblade38/product-preview-card-component",
    about: "A simple product card component",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Blog-preview-card/",
    about: "A simple blog preview card made with html tailwindcss",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/FrontendChallenge01/",
    about: "A simple recipe page made with html tailwindcss",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/social-links-profile/",
    about: "A social link sharing profile made with html tailwindcss",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/FAQ-accordion/",
    about: "A FAQ accordion",
    completed: true,
    techStack: ["HTML", "TailwindCss", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Html-Cv/",
    about: "A single-page HTML CV to showcase your career history",
    completed: true,
    techStack: ["HTML", "TailwindCss"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/portfolio-html/",
    about: "Simple HTML only website with multiple pages",
    completed: true,
    techStack: ["HTML"],
  },
  {
    name: "",
    githubLink: "https://github.com/Victorblade38/basic-html-portfolio-css",
    about: "A simple Personal portfolio",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Change-log/",
    about: "A changelog component for a website using HTML and CSS.",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/different-cards/",
    about: "Testimonial cards for a website using HTML and CSS.",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Datepicker-Desgin/",
    about: "A simple datepicker UI using HTML and CSS.",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/accessible-form-design/",
    about: "An accessible form UI using HTML and CSS",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/ImageGrid/",
    about: "A grid layout of images using HTML and CSS.",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Tooltip-desgin/",
    about: "A tooltip for navigation items using only HTML and CSS.",
    completed: true,
    techStack: ["HTML", "CSS"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Tabs/",
    about: "A simple tabs component using HTML, CSS, and JavaScript.",
    completed: true,
    techStack: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Cookie-consent/",
    about: "A textarea with live character count and a max character limit.",
    completed: true,
    techStack: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Accordian/",
    about: "An accordion component using HTML, CSS, and JavaScript.",
    completed: true,
    techStack: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://victorblade38.github.io/Custom-dropdown/",
    about: "A custom dropdown using HTML, CSS, and JavaScript.",
    completed: true,
    techStack: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "",
    githubLink: "https://github.com/Victorblade38/githubRepoFinder",
    about: "A GitHub random repository finder using GitHub API.",
    completed: true,
    techStack: ["HTML", "CSS", "Javascript"],
  },
];

export default simpleprojects;
